import express from 'express';
import path from 'path';
import dotenv from 'dotenv';
import { createServer as createViteServer } from 'vite';

dotenv.config();

const app = express();
const PORT = 3000;

// PayPhone Ecuador Constants & Secrets (loaded securely from environment)
const PAYPHONE_API_BASE = 'https://pay.payphonetodoesposible.com/api/button';
const PAYPHONE_SECRET_TOKEN = process.env.PAYPHONE_SECRET_TOKEN || process.env.PAYPHONE_BEARER_TOKEN || 'RLGD9J-uehwxt_6X5D0OxiG_N9gj652oouLMjfu5ldRtB3KzTwF7YrW9SLcaoYCQZM5K-sJem-RL6iByAakcn7XdVP_l-iHrshBxIkcRsqiNaeWnOBvY06IJEAzD0IEmNFxR_3NB1qIaxRRE8fRDogBggC33-1R-BGdHgKVUMT8L5EUWH1aZ2BqGpQHaacu3QjFEa8ds-lxsRTrie5vb7cMYIoaYJ_IbJmV8tMNBRwRY526I3E1AU4FRSB5Fa_vJ3h7JJE9WGS7OPrAaPYZScnZjSIt7ECQJJ5Z5lbpiQ9-E7De1lIE_Atfr6d_i7dM7aY-ejesg1pQU1IujFy5wZPgMLcE';
const PAYPHONE_STORE_ID = process.env.PAYPHONE_STORE_ID || '138280';
const PAYPHONE_APP_ID = process.env.PAYPHONE_APP_ID || 'DTrLfqcObUmyYxjr8FE7Aw';
const PAYPHONE_RESPONSE_URL = process.env.PAYPHONE_RESPONSE_URL || 'https://sherepunjabecu.com';

// Helper to format detailed PayPhone error messages into readable strings
function formatPayPhoneError(data: any): string {
  if (!data) return 'Error desconocido de pasarela';
  if (typeof data === 'string') return data;

  let msg = data.message || data.error || data.payphoneMessage || '';
  if (data.errors) {
    if (typeof data.errors === 'string') {
      msg += (msg ? ': ' : '') + data.errors;
    } else if (Array.isArray(data.errors)) {
      msg += (msg ? ': ' : '') + data.errors.map((e: any) => (typeof e === 'object' ? JSON.stringify(e) : String(e))).join(', ');
    } else if (typeof data.errors === 'object') {
      const details = Object.entries(data.errors)
        .map(([k, v]) => `${k}: ${Array.isArray(v) ? v.join(', ') : (typeof v === 'object' ? JSON.stringify(v) : String(v))}`)
        .join('; ');
      msg += (msg ? ': ' : '') + details;
    }
  }
  return msg || JSON.stringify(data, null, 2);
}

// In-Memory Idempotency Cache to prevent duplicate transaction confirmations
interface ConfirmedTransactionRecord {
  clientTxId: string;
  transactionId: number | string;
  amount: number;
  authorizationCode?: string;
  cardBrand?: string;
  lastDigits?: string;
  confirmedAt: string;
  status: string;
}

const confirmedTransactions = new Map<string, ConfirmedTransactionRecord>();

// Parse JSON request bodies
app.use(express.json());

// ============================================================================
// 1. PayPhone Configuration Endpoint (Public metadata only, NO secrets)
// ============================================================================
app.get('/api/payphone/config', (_req, res) => {
  res.json({
    appId: PAYPHONE_APP_ID,
    storeId: PAYPHONE_STORE_ID,
    responseUrl: PAYPHONE_RESPONSE_URL,
    currency: 'USD',
    ivaRate: 0.15, // 15% Ecuadorian IVA
  });
});

// ============================================================================
// 2. /api/create-payment (PayPhone Button Prepare Endpoint)
// Accepts amount and clientTxId. Calls https://pay.payphonetodoesposible.com/api/button/Prepare
// Returns payWithPayPhone URL generated by PayPhone.
// ============================================================================
app.post(['/api/create-payment', '/api/payphone/create'], async (req, res) => {
  try {
    const {
      amount: rawAmount,
      totalAmount,
      totalDollars,
      clientTxId: rawClientTxId,
      clientTransactionId,
      reference,
      customerEmail,
      customerPhone,
      email,
      phoneNumber,
    } = req.body || {};

    const total = Number(rawAmount ?? totalAmount ?? totalDollars ?? 0);
    if (!total || total <= 0) {
      return res.status(400).json({
        success: false,
        error: 'Amount must be a positive number greater than 0',
      });
    }

    // 1. Amount Breakdown Formula: Pure integer in cents (e.g. 11.85 -> 1185)
    // PayPhone strictly requires: amount = amountWithoutTax + amountWithTax + tax + service + tip
    const totalCents = Math.round(total * 100);
    const amountWithoutTax = totalCents;
    const amountWithTax = 0;
    const tax = 0;
    const service = 0;
    const tip = 0;

    // 2. Data Types & Formats
    // Clean alphanumeric string (max 50 characters, NO spaces, NO special characters except hyphens)
    const rawTxId = clientTransactionId || rawClientTxId || `SHERE-${Date.now()}`;
    const cleanClientTxId = String(rawTxId)
      .replace(/[^a-zA-Z0-9-]/g, '')
      .slice(0, 50);

    // Reference: plain string without unsupported characters (max 30 characters)
    const cleanReference = String(reference || `Order ${cleanClientTxId}`)
      .replace(/[^a-zA-Z0-9 -]/g, '')
      .trim()
      .slice(0, 30);

    // Clean secret token and store ID from environment variables
    const rawToken = process.env.PAYPHONE_SECRET_TOKEN || process.env.PAYPHONE_BEARER_TOKEN || PAYPHONE_SECRET_TOKEN;
    const cleanToken = rawToken ? rawToken.replace(/^Bearer\s+/i, '').replace(/["'\r\n]/g, '').trim() : '';
    const rawStoreId = process.env.PAYPHONE_STORE_ID || PAYPHONE_STORE_ID || '138280';
    const cleanStoreId = String(rawStoreId).replace(/["'\r\n]/g, '').trim();

    // Clean phone number (numeric digits only)
    const rawPhone = phoneNumber || customerPhone || '';
    const cleanPhone = rawPhone ? String(rawPhone).replace(/\D/g, '') : '';

    const rawEmail = email || customerEmail || '';
    const cleanEmail = rawEmail ? String(rawEmail).trim() : '';

    const payload: any = {
      amount: totalCents,
      amountWithoutTax: amountWithoutTax,
      amountWithTax: amountWithTax,
      tax: tax,
      service: service,
      tip: tip,
      currency: 'USD',
      clientTransactionId: cleanClientTxId,
      storeId: cleanStoreId,
      reference: cleanReference || 'Sher-e-Punjab Order',
      responseUrl: PAYPHONE_RESPONSE_URL,
      cancellationUrl: PAYPHONE_RESPONSE_URL,
    };

    if (cleanEmail) {
      payload.email = cleanEmail;
    }
    if (cleanPhone) {
      payload.phoneNumber = cleanPhone;
    }

    console.log(`[PayPhone API] Calling Prepare API for clientTxId ${cleanClientTxId}:`, JSON.stringify(payload, null, 2));

    const payphoneHeaders = {
      'Authorization': `Bearer ${cleanToken}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    };

    const response = await fetch(`${PAYPHONE_API_BASE}/Prepare`, {
      method: 'POST',
      headers: payphoneHeaders,
      body: JSON.stringify(payload),
    });

    const responseText = await response.text();
    console.log(`[PayPhone API] Raw Prepare Status: ${response.status}`);

    let data: any = null;
    try {
      data = JSON.parse(responseText);
    } catch {
      data = { rawText: responseText };
    }

    console.log('[PayPhone API Prepare Response]:', JSON.stringify(data, null, 2));

    if (!response.ok) {
      console.error('PayPhone Error Detail:', JSON.stringify(data, null, 2));
      const formattedError = formatPayPhoneError(data);

      return res.status(response.status || 400).json({
        success: false,
        error: formattedError,
        message: formattedError,
        payphoneMessage: formattedError,
        details: data,
        sentPayload: payload,
      });
    }

    const token =
      data?.token ||
      (typeof data === 'string' && data.length > 20 ? data : null) ||
      data?.payUrl ||
      data?.paymentUrl;

    const paymentId = data?.paymentId || data?.id || data?.transactionId || null;

    // Generate payWithPayPhone URL from PayPhone response or token
    const payWithPayPhone =
      data?.payWithPayPhone ||
      (token ? `https://pay.payphonetodoesposible.com/pay?token=${encodeURIComponent(token)}` : null);

    if (!payWithPayPhone) {
      console.error('PayPhone Error Detail (No pay URL returned):', JSON.stringify(data, null, 2));
      const errMsg = formatPayPhoneError(data) || 'No payment URL or token received from PayPhone';
      return res.status(400).json({
        success: false,
        error: errMsg,
        message: errMsg,
        payphoneMessage: errMsg,
        details: data,
      });
    }

    console.log(`[PayPhone API] Generated payWithPayPhone URL for ${cleanClientTxId}:`, payWithPayPhone);

    return res.json({
      success: true,
      paymentUrl: payWithPayPhone,
      payWithPayPhone: payWithPayPhone,
      token: token,
      paymentId: paymentId,
      clientTxId: cleanClientTxId,
      clientTransactionId: cleanClientTxId,
      storeId: cleanStoreId,
      appId: PAYPHONE_APP_ID,
      amount: total,
      amountInCents: totalCents,
    });
  } catch (error: any) {
    console.error('PayPhone Error Detail (Exception):', error);
    const errString = error?.message ? String(error.message) : JSON.stringify(error, null, 2);
    return res.status(500).json({
      success: false,
      error: errString,
      message: errString,
      payphoneMessage: errString,
    });
  }
});

// ============================================================================
// 3. /api/confirm-payment (PayPhone Button V2/Confirm Endpoint)
// Accepts id and clientTxId. Calls https://pay.payphonetodoesposible.com/api/button/V2/Confirm
// Returns 'Approved' status when the customer finishes paying.
// ============================================================================
app.post(['/api/confirm-payment', '/api/payphone/confirm'], async (req, res) => {
  try {
    const { id, clientTxId, clientTransactionId, paymentId } = req.body;
    const targetId = id || paymentId;
    const targetClientTxId = clientTxId || clientTransactionId;

    if (!targetClientTxId) {
      return res.status(400).json({
        success: false,
        error: 'clientTxId is required for payment confirmation.',
      });
    }

    // 1. Check idempotency: If this clientTxId was already confirmed, return cached Approved success
    if (confirmedTransactions.has(targetClientTxId)) {
      const cached = confirmedTransactions.get(targetClientTxId)!;
      return res.json({
        success: true,
        isPaid: true,
        status: 'Approved',
        transactionStatus: 'Approved',
        isCached: true,
        payment: cached,
      });
    }

    console.log(`[PayPhone API] Confirming transaction server-side. Target ID: ${targetId}, ClientTxId: ${targetClientTxId}...`);

    const payload = {
      id: typeof targetId === 'string' && /^\d+$/.test(targetId) ? parseInt(targetId, 10) : (targetId || 0),
      clientTxId: String(targetClientTxId),
    };

    let data: any = null;
    const rawToken = process.env.PAYPHONE_SECRET_TOKEN || process.env.PAYPHONE_BEARER_TOKEN || PAYPHONE_SECRET_TOKEN;
    const cleanToken = rawToken ? rawToken.replace(/["'\r\n]/g, '').trim() : '';

    const headers = {
      'Authorization': `Bearer ${cleanToken}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    };

    // Try V2/Confirm first as requested by official PayPhone V2 specifications
    let response = await fetch(`${PAYPHONE_API_BASE}/V2/Confirm`, {
      method: 'POST',
      headers: headers,
      body: JSON.stringify(payload),
    });

    if (!response.ok && response.status === 404) {
      // Fallback to /Confirm endpoint
      response = await fetch(`${PAYPHONE_API_BASE}/Confirm`, {
        method: 'POST',
        headers: headers,
        body: JSON.stringify(payload),
      });
    }

    const responseText = await response.text();
    try {
      data = JSON.parse(responseText);
    } catch {
      data = null;
    }

    console.log(`[PayPhone API] Confirm response status ${response.status}:`, data);

    // Check PayPhone approved criteria strictly
    const isApproved =
      data?.transactionStatus === 'Approved' ||
      data?.statusCode === 3 ||
      data?.transactionStatus === 'Aprobada' ||
      (data?.status === 'Approved' || data?.status === 'Aprobada');

    if (isApproved && data) {
      const paymentRecord: ConfirmedTransactionRecord = {
        clientTxId: String(targetClientTxId),
        transactionId: String(data.transactionId || targetId || 'APPROVED'),
        amount: data.amount ? data.amount / 100 : Number(req.body.amount || 0),
        authorizationCode: data.authorizationCode || `AUTH-${Date.now().toString().slice(-6)}`,
        cardBrand: data.cardBrand || data.cardType || 'PayPhone Ecuador',
        lastDigits: data.lastDigits || '',
        confirmedAt: new Date().toISOString(),
        status: 'Approved',
      };

      // Store in idempotency cache
      confirmedTransactions.set(targetClientTxId, paymentRecord);

      return res.json({
        success: true,
        isPaid: true,
        status: 'Approved',
        transactionStatus: 'Approved',
        payment: {
          ...paymentRecord,
          email: data.email || '',
          phoneNumber: data.phoneNumber || '',
          message: data.message || 'Pago aprobado por PayPhone Ecuador',
        },
      });
    }

    // Pending / Processing or Rejected state
    const currentStatus = data?.transactionStatus || (data?.statusCode === 2 ? 'Pending' : 'Pending');
    const errorMessage =
      data?.message ||
      (data?.transactionStatus ? `Transacción en estado: ${data.transactionStatus}` : 'Esperando confirmación de pago...');

    return res.json({
      success: false,
      isPaid: false,
      status: currentStatus,
      transactionStatus: currentStatus,
      error: errorMessage,
      details: data,
    });
  } catch (error: any) {
    console.error('[PayPhone API] Exception in /api/confirm-payment:', error);
    return res.status(500).json({
      success: false,
      isPaid: false,
      status: 'Error',
      error: error?.message || 'Error al comunicarse con el servidor de PayPhone',
    });
  }
});

// ============================================================================
// 4. Vite Dev Server & Production Static Asset Serving
// ============================================================================
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (_req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`[Sher E Punjab Server] Running on http://0.0.0.0:${PORT}`);
    console.log(`[Sher E Punjab Server] PayPhone Ecuador gateway initialized securely.`);
  });
}

startServer();
